### PR TITLE
Replace Moshi by Kotlin Serializer

### PR DESCRIPTION
**Pull request by mirland**
Discussed here in https://github.com/dropbox/Store/issues/339#issuecomment-988020225

### Preview

https://user-images.githubusercontent.com/8472881/145057459-5ce10e60-3302-4e1b-8502-be24d0d8dac9.mp4

### CODE REVIEW

**Review by digitalbuddha — APPROVED** [review]
waiting for another +1 as I have never used kotlin serialization myself

**Review by handstandsam — APPROVED** [review]
Looks fine.  I'd prefer to not see such a big formatting change in dependencies, but appreciate that you removed `jcenter()` 😄

**Comment by digitalbuddha** [comment]
Agreed could you revert the formatting changes and then I’ll merge

**Comment by mirland** [comment]
Sure. However, if I do that, you will not be able to use the AS indentation anymore (the arrange code feature), because the keys are aligned using the max length key, in this case, `retrofitSerializerConverter`. Is it a problem for you? if it's not a problem for you I can revert the formatting.

**Pull request merged**
