### PR TITLE
Replace Retrofit's deprecated Deferred CallAdapter with its built-in suspend support.

### PR DESCRIPTION
**Pull request by gdingenen**
The sample app is using the deprecated Retrofit coroutine adapter with Deferred.

It is advised to migrate to Retrofit's built-in suspend support.

More details at https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter

### CODE REVIEW

**Comment by digitalbuddha** [comment]
Coudl you please sign our cla and let us know when done. It is linked in the pr template. Thank you kindly

**Comment by digitalbuddha** [comment]
Thank you for contribution! Was not available at the time :-)

**Comment by gdingenen** [comment]
I have signed the CLA. Can you check if this was successful?

**Comment by digitalbuddha** [comment]
All set, we are still working on cla assistant so I can be less annoying :-)

**Pull request merged**
