### PR TITLE
Update dependencies and clean up unused ones

### PR DESCRIPTION
**Pull request by ychescale9**

### CODE REVIEW

**Comment by ychescale9** [comment]
Looks like some licences have not been accepted in the travis setup
```
build-tools;29.0.2 Android SDK Build-Tools 29.0.2
platforms;android-29 Android SDK Platform 29
```

Do you want to add these on travis or do you want me to revert the SDK and build tools changes?

**Comment by ychescale9** [comment]
And we can remove CircleCI now?

**Comment by digitalbuddha** [comment]
you can add to travis build script I'll be removing the circle one in another pr

**Comment by digitalbuddha** [comment]
Thank you!

**Pull request merged**
